@echo "================================"
@echo "Доступные команды:"
@echo " ==> make install    - синхронизировать окружение"
@echo " ==> make test       - прогнать тесты"
@echo " ==> make typecheck  - проверить аннотации (mypy)"
@echo " ==> make check      - все проверки разом"
@echo " ==> make build      - собрать пакет"
@echo " ==> make publish    - опубликовать на PyPI"
@echo " ==> make clean      - удалить артефакты сборки"
